# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YPIMClient' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'ProtocolBuffers-Swift'

  target 'YPIMClientTests' do
    inherit! :search_paths
   

  end

  target 'YPIMClientUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
