# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '面向协议-请求数据' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 面向协议-请求数据

pod 'Alamofire', '~> 4.7.3'

  target '面向协议-请求数据Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '面向协议-请求数据UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
